### ISSUE TITLE
Add Etcher Docs

### ISSUE THREAD

**Issue by RobLoach** [lakkatv/lakka-website#24]
https://etcher.io/

Works for Mac, Windows and Linux.

**Comment by Aaahh** [comment]
I'm assuming this would go in place of the windows, mac, and Linux installation instructions for PC?
I feel like the instructions are simple enough at this time, a simple dd shouldn't be too hard

**Comment by RobLoach** [comment]
Perhaps a note at the bottom about it. Some find a GUI easier to use than using the command line.

**Comment by clach04** [comment]
The website today does link to balenaEtcher (note using the old etcher.io URL) e.g. see http://www.lakka.tv/get/windows/rpi2/install/.

Is this still relevant?

**Comment by RobLoach** [comment]
Done! Tahnksa  lot/
