### ISSUE TITLE
Broken links

### ISSUE THREAD

**Issue by vffhr** [lakkatv/lakka-website#63]
This page: http://www.lakka.tv/doc/Input-settings/
has this broken image link: http://wiki.libretro.com/images/6/68/Retropad_360pad.png

This page (and similar pages for other systems): http://www.lakka.tv/get/windows/rpi2/install/
has a broken link at the bottom with this text: "alternative flashing methods"

This page: http://www.lakka.tv/articles/
has links at the bottom to duplicate tags with different casing with broken links:

* Gamegirl (lower case second "g")
* Mupen64plus (upper case "M")
* Odroid-C1 (upper case "C")

**Comment by ToKe79** [comment]
@kivutar the link to alternative flash methods is a link to the /doc/ section, which is generated from the GitHub wiki pages. My best guess is that after recompiling the web page (bundle exec nanoc), this section was not recompiled/new pages added.

**Comment by ToKe79** [comment]
broken image -> is fixed
link to alternative flashing methods -> is fixed
tags -> links work, but the tags should have consistent case (relevant articles need to be edited/fixed)
otherwise this bug can be closed
