### ISSUE TITLE
Raspberry Pi 4 install doc not found

### ISSUE THREAD

**Issue by mnilsson23** [lakkatv/lakka-website#82]
## Documents
https://www.lakka.tv/get/windows/rpi4/install

## Proposed changes
Step through the install workflow on the website after selecting windows + raspberry pi 4. After downloading the image the "Next step" button takes to you to the above link that 404s,

**Comment by natinusala** [comment]
Thanks for reporting that, I'll fix it asap

**Comment by natinusala** [comment]
Fixed by 5958109
