### ISSUE TITLE
Firefox or wget complain about TLS

### ISSUE THREAD

**Issue by W73** [lakkatv/lakka-website#88]
wget https://le.builds.lakka.tv/RPi2.RPi4.arm/Lakka-RPi2.RPi4.arm-2.3.2.img.gz 
--2020-03-28 12:51:25--  https://le.builds.lakka.tv/RPi2.RPi4.arm/Lakka-RPi2.RPi4.arm-2.3.2.img.gz
Resolving le.builds.lakka.tv (le.builds.lakka.tv)... 104.24.108.116, 104.24.109.116, 2606:4700:3030::6818:6d74, ...
Connecting to le.builds.lakka.tv (le.builds.lakka.tv)|104.24.108.116|:443... connected.
GnuTLS: A TLS fatal alert has been received.
GnuTLS: received alert [40]: Handshake failed
Unable to establish SSL connection.

**Comment by gouchi** [comment]
It is working.

```
wget "https://le.builds.lakka.tv/legacy-2.3/RPi2.RPi4.arm/Lakka-RPi2.RPi4.arm-2.3.2.img.gz"
--2021-05-23 11:10:46--  https://le.builds.lakka.tv/legacy-2.3/RPi2.RPi4.arm/Lakka-RPi2.RPi4.arm-2.3.2.img.gz
Loaded CA certificate '/etc/ssl/certs/ca-certificates.crt'
Resolving le.builds.lakka.tv (le.builds.lakka.tv)... 195.201.56.250, 2a01:4f8:13b:945::2
Connecting to le.builds.lakka.tv (le.builds.lakka.tv)|195.201.56.250|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 402748282 (384M) [application/octet-stream]
Saving to: 'Lakka-RPi2.RPi4.arm-2.3.2.img.gz.2'
```
